{{- if .Values.prometheusRules.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "prometheus-whistleblower.name" . }}
{{- if .Values.serviceMonitor.labels }}
  labels:
{{- range $key, $value := .Values.serviceMonitor.labels }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
{{- else }}
  labels: {}
{{- end }}
spec:
  groups:
    - name: prometheus-whistleblower.rules
      rules:
        - alert: WhistleblowerAlerts
          expr: '{release="{{ include "prometheus-whistleblower.fullname" . }}"}'
          annotations:
            summary: "Whistleblower raising an alert"
            description: "The whistleblower service is exposing metrics."
{{- end }}
