{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "prometheus-whistleblower.name" . }}
{{- if .Values.serviceMonitor.labels }}
  labels:
{{- range $key, $value := .Values.serviceMonitor.labels }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
{{- else }}
  labels: {}
{{- end }}
spec:
  selector:
    matchLabels:
      app: {{ include "prometheus-whistleblower.name" . }}
  endpoints:
    - port: http
      interval: {{ .Values.serviceMonitor.interval }}
      relabelings:
        - sourceLabels: []
          targetLabel: release
          replacement: {{ include "prometheus-whistleblower.fullname" . }}

  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
