replicaCount: 1

image:
  repository: ghcr.io/chazapp/prometheus-whistleblower
  tag: "0.0.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: whistleblower.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

serviceMonitor:
  enabled: false
  interval: 30s
  labels: []


prometheusRules:
  enabled: false
  labels: []
  rules:
    - alert: WhistleblowerDown
      expr: up{job="prometheus-whistleblower"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Whistleblower service is down"
        description: "The whistleblower service has been unreachable for more than 1 minute."

